apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev
  namespace: k8-demo-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-dev
      env: dev
  template:
    metadata:
      labels:
        app: app-dev
        env: dev
    spec:
      containers:
      - name: app
        image: colbyx20/k8-demo:1.0.5
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          failureThreshold: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          failureThreshold: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "150Mi"
            cpu: "100m"
          limits:
            memory: "550Mi"
            cpu: "150m"
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: devcf
