apiVersion: batch/v1
kind: Job
metadata:
  labels:
    env: dev
  namespace: k8-demo-dev
  name: load-generator-job
spec:
  completions: 2
  parallelism: 2
  template:
    spec:
      containers:
      - image: busybox
        name: load-generator
        command: ["sh", "-c", "while true; do wget -q -O- http://app-svc-dev:3000; echo '\n'; done"]
      restartPolicy: Never
  backoffLimit: 10