apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa-sit
  namespace: k8-demo-sit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-k8s
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50