apiVersion: v1
kind: Service
metadata:
  name: app-svc-sit
  namespace: k8-demo-sit
spec:
  selector:
    app: app-sit
    env: sit
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer